process-dispatchers:
  pd_0:
    config:
      processdispatcher:
        engines:
          default:
            deployable_type: eeagent
            slots: 4
            base_need: 1
nodes:
  nodeone:
    dt: eeagent
    process-dispatcher: pd_0
    eeagents:
      eeagent_nodeone:
        launch_type: supd
        logfile: /tmp/eeagent_nodeone.log
provisioners:
  provisioner_0:
    config:
      replica_count: 5
      provisioner:
        default_user: default
        dtrs: epu.localdtrs.LocalDTRS
epums:
  epum_0:
    config:
      epumanagement:
        default_user: default
        provisioner_topic: provisioner_0
      logging:
        handlers:
          file:
            filename: /tmp/epum_0.log
